apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: 5spring 
  janus-idp.io/tekton: 5spring
  backstage.io/kubernetes-id: 5spring
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: 5spring
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml