apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: 5spring
  janus-idp.io/tekton: 5spring
  backstage.io/kubernetes-id: 5spring
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: 5spring
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
