apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: 5spring
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 5spring 
  name: 5spring
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: 5spring 
